package com.stayfit.app

object Constants {
    val SUCCESS_RESULT = 0
    val FAILURE_RESULT = 1

    val USE_ADDRESS_NAME = 1
    val USE_ADDRESS_LOCATION = 2

    val PACKAGE_NAME = "com.example.maddi.mapsandyoutubehw11"
    val RECEIVER = "$PACKAGE_NAME.RECEIVER"
    val RESULT_DATA_KEY = "$PACKAGE_NAME.RESULT_DATA_KEY"
    val RESULT_ADDRESS = "$PACKAGE_NAME.RESULT_ADDRESS"
    val LOCATION_LATITUDE_DATA_EXTRA = "$PACKAGE_NAME.LOCATION_LATITUDE_DATA_EXTRA"
    val LOCATION_LONGITUDE_DATA_EXTRA = "$PACKAGE_NAME.LOCATION_LONGITUDE_DATA_EXTRA"
    val LOCATION_NAME_DATA_EXTRA = "$PACKAGE_NAME.LOCATION_NAME_DATA_EXTRA"
    val FETCH_TYPE_EXTRA = "$PACKAGE_NAME.FETCH_TYPE_EXTRA"

}